[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "CHEM10_Harvard"
version = "0.0.1"
dependencies = [
  "numpy",
  "pandas",
  "matplotlib",
  "telemetrix",
  "jupyter",
  "ipykernel",
  "dtw-python"
]
requires-python = ">=3.12"
authors = [
  {name = "David Sauer", email = "davidsauer@college.harvard.edu"},
  {name = "Austin Wang"},
  {name = "Mara Casabeer"}
]

[project.optional-dependencies]
test = [
  "pytest",
  "pytest-cov"
]

[tool.hatch.build.targets.wheel]
packages = ["src/CHEM10_Harvard"]

[tool.pytest.ini_options]
addopts = [
    "-m not physical",
]
markers = [
    "physical: marks tests that need a physical setup",
    "environment: marks tests that verify the environment setup"
]