[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "CHEM10_Harvard"
version = "0.0.2"
dependencies = [
  "numpy>=2.4.3",
  "pandas>=3.0.1",
  "matplotlib>=3.10.8",
  "telemetrix>=1.46",
  "jupyter>=1.1.1",
  "ipykernel>=7.2.0",
  "dtw-python>=1.7.5"
]
requires-python = ">=3.12"
authors = [
  {name = "David Sauer"},
  {name = "Austin Wang"},
  {name = "Mara Casabeer"}
]
description = "A package for interfacing with the spectrometer built by students in CHEM 10"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.txt"]

[project.urls]
Code = "https://github.com/biotungsten/CHEM10_Harvard"

[project.optional-dependencies]
test = [
  "pytest>=9.0.2",
  "pytest-cov>=7.1.0"
]

[tool.hatch.build.targets.wheel]
packages = ["src/CHEM10_Harvard"]

[tool.pytest.ini_options]
addopts = [
    "-m not physical",
]
markers = [
    "physical: marks tests that need a physical setup",
    "environment: marks tests that verify the environment setup"
]